module.exports = {
  CHANGE_EVENT: "CHANGE_EVENT",

  USER_ACTIONS: {
    FILTER_USERS: "FILTER_USERS",
    SORT_USERS: "SORT_USERS"
  },

  USER_SERVER_ACTIONS: {
    GET_USERS: "GET_USERS",
  },

  LOGIN_ACTIONS: {
    AUTHENTICATE_USER: "AUTHENTICATE_USER"
  }
};
